name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read
  packages: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show files (debug)
        run: ls -la

      - name: Set lowercase image name
        run: |
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          echo "IMAGE_NAME=ghcr.io/$OWNER/statuspulse" >> $GITHUB_ENV
          echo "IMAGE_TAG=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Verify Dockerfile exists
        run: |
          if [ ! -f Dockerfile ]; then
            echo "Dockerfile not found"
            exit 1
          fi

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          set -e
          echo "Building Docker image..."
          docker build -t $IMAGE_NAME:$IMAGE_TAG .

      - name: Push Docker image
        run: |
          set -e
          echo "Pushing Docker image..."
          docker push $IMAGE_NAME:$IMAGE_TAG
